### ISSUE TITLE
More uniqueness to entity_ids

### ISSUE THREAD

**Issue by dagobert** [pszafer/home-assistant-bosch-custom-component#21]
It would be great if the entity_id would be more unique. Having a sensor called `sensor.outdoor_temperature` has a likelihood of conflicting with existing sensors due to its shortness.
More so, imho it is not very much identifiable to be a sensor created by your component. 

Even more important, If someone has more than one heater you are certainly running into naming problems. I know this scenario might be not very likely but why not let it be the factor for this change.
  
**Describe the solution you'd like**
I would suggest a yaml option `name` which is used to identify the heater. This could be part of the naming convention for the sensor entity_id. 
To not break the existing configurations of others, set its default to empty string and when given prefix and suffix it with `_`

Example:
```
bosch:
  - address: <IP ADDRESS>
    password: "YOUR GATEWAY PASSWORD"
    access_token: "Access key to your gateway"
    name: mysuperheater
```
 Result:

`sensor.mysuperheater_outdoor_temperature`
